**660710690 กมลเนตร ภูชา**



In [2]:
!pip install -U pip transformers

In [3]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM


In [4]:
checkpoint = 'facebook/nllb-200-distilled-600M'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

In [5]:
print(f"{len(tokenizer.vocab)}\n")

tokenizer.vocab

256204



{'▁እዚ': 12149,
 '▁어머니의': 247886,
 '▁ortam': 194759,
 'skimi': 133643,
 'شو': 95266,
 '▁świata': 207188,
 '这': 249852,
 '▁نفسي': 144439,
 '▁podle': 54422,
 '▁Ilay': 148796,
 'ration': 137231,
 '▁දව': 95250,
 '▁ಅಪ್ಪ': 203009,
 'روپ': 183675,
 '▁çê': 87359,
 'rete': 98451,
 '▁তুল': 61570,
 '▁tagħmir': 142578,
 '▁telefoni': 74705,
 '▁Ալ': 205466,
 '▁përfaqë': 172349,
 'ទាន': 112714,
 '全体が': 195929,
 '▁internet': 12240,
 'únta': 191581,
 '▁個人': 215477,
 'ime': 1321,
 '▁보내고': 181819,
 '▁প্রশাস': 245293,
 'வ்': 19240,
 'ひどい': 151988,
 '▁Kitob': 86825,
 '▁Vod': 205859,
 '▁Joker': 243989,
 'meleri': 135798,
 'ಷಿ': 171366,
 '野': 250740,
 '▁middag': 153481,
 '▁دامنه': 137744,
 'ቆብ': 165776,
 '▁сән': 112955,
 '▁espesi': 198264,
 '▁relatati': 71030,
 '▁ổn': 102713,
 'werken': 173559,
 'པར་མི་': 150839,
 '▁vyš': 70161,
 '▁ары': 54178,
 'なんですか': 234003,
 '▁Reserve': 180264,
 'မည်။': 50029,
 'лектәр': 118581,
 '▁wayek': 159170,
 '▁ٽ': 19681,
 '▁שנית': 223941,
 '▁panem': 169517,
 '▁अभ्यास': 73615,
 '▁G

In [6]:
thai_char_min = 0x0E00
thai_char_max = 0x0E7F

thai_tokens = [
    token for token in tokenizer.vocab.keys()
    if any(thai_char_min <= ord(char) <= thai_char_max for char in token)
]

thai_token_count = len(thai_tokens)
sample_size = 20
thai_tokens_sample = thai_tokens[:sample_size]


print(f"{thai_token_count}\n")
for token in thai_tokens_sample:
  print(token)

1712

เส้น
อื่น
ศา
ัง
ว่าเรา
ญ
▁เหล่า
ูด
โท
บัง
เปล่า
▁ลบ
จึง
หก
รา
เยอะ
▁ของ
เขาม
จุด
▁ๆ


In [7]:
import tensorflow as tf
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import numpy as np
import math

In [8]:
sentence = 'Work hard, play harder'

In [9]:
cleaned_sentence = sentence.replace(',', '')
cleaned_sentence

'Work hard play harder'

In [10]:
words = cleaned_sentence.split()
words

['Work', 'hard', 'play', 'harder']

In [11]:
sorted_words = sorted(words)
sorted_words

['Work', 'hard', 'harder', 'play']

In [12]:
dc = {word: index for index, word in enumerate(sorted_words)}
dc

{'Work': 0, 'hard': 1, 'harder': 2, 'play': 3}

In [13]:
sentence_int = tf.constant(
    [dc[s] for s in sentence.replace(',', '').split()],
    dtype=tf.int32
)

In [14]:
print(sentence)
print(sentence_int)

Work hard, play harder
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [15]:
# สร้าง embedding layer
tf.random.set_seed(123)
vocab_size = 50_000
embedding_dim = 2

embed = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim)

In [16]:
embedded_sentence = embed(sentence_int)

In [17]:
embedded_sentence

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.03446851, -0.00357019],
       [-0.01995064, -0.00613034],
       [-0.01702313,  0.0238638 ],
       [ 0.00711641, -0.0311882 ]], dtype=float32)>

In [18]:
tf.random.set_seed(123)
vocab_size = 50_000
embedding_dim = 2

dummy_input = tf.constant([0, 1, 2], dtype=tf.int32)

# Case 1 Default initializer (RandomUniform(-0.05, 0.05))
embed_default = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim)
_ = embed_default(dummy_input) # เรียกใช้งาน layer เพื่อสร้าง weights
weights_default = embed_default.get_weights()[0].flatten()
weights_default.shape


(100000,)

In [19]:
# Case 2 GlorotUniform initializer
tf.random.set_seed(123)
embed_glorot = tf.keras.layers.Embedding(
    input_dim=vocab_size,
    output_dim=embedding_dim,
    embeddings_initializer=tf.keras.initializers.GlorotUniform()
)
_ = embed_glorot(dummy_input) # เรียกใช้งาน layer เพื่อสร้าง weights
weights_glorot = embed_glorot.get_weights()[0].flatten()
weights_glorot.shape

(100000,)

In [20]:
fig = make_subplots(rows=1, cols=1)

fig.add_trace(go.Histogram(x=weights_default, nbinsx=50, name="Default Uniform [-0.05, 0.05]", opacity=0.6))
fig.add_trace(go.Histogram(x=weights_glorot, nbinsx=50, name="Glorot Uniform", opacity=0.6))

fig.update_layout(
    title_text='Embedding Layer Initialization Comparison',
    xaxis_title_text='Weight values',
    yaxis_title_text='Frequency',
    barmode='overlay',
    legend_orientation="h",
    legend_yanchor="bottom",
    legend_y=1.02,
    legend_xanchor="right",
    legend_x=1
)

fig.show()

print("Default initializer range ", weights_default.min(), weights_default.max())
print("Glorot initializer range ", weights_glorot.min(), weights_glorot.max())

Default initializer range  -0.04999397 0.049997877
Glorot initializer range  -0.010954177 0.010954213


In [21]:
def glorot_uniform_limits(fan_in, fan_out):
    limit = math.sqrt(6.0 / (fan_in + fan_out))
    a, b = -limit, limit
    return a, b

# ตัวอย่าง Embedding layer (vocab_size=50000, embedding_dim=2)
fan_in = 50000
fan_out = 2

a, b = glorot_uniform_limits(fan_in, fan_out)
print("Glorot Uniform a =", a)
print("Glorot Uniform b =", b)

Glorot Uniform a = -0.010954232067652772
Glorot Uniform b = 0.010954232067652772


In [22]:
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [23]:
token_embedding_layer = model.model.encoder.embed_tokens
token_embedding_layer.weight.shape

torch.Size([256206, 1024])

In [24]:
long_sentence = "In the vast realm of natural language processing, understanding the nuances of how models handle sequential data is crucial. Positional encoding plays a vital role in providing this essential information to the model, allowing it to differentiate between words at different positions in a sentence, which is fundamental for tasks like translation, summarization, and text generation."

In [25]:
tokens = tokenizer(long_sentence, return_tensors="pt")

print(tokens['input_ids'][0])

tensor([256047,    717,    349,  14430,  12284, 248070,    452,  25307,  65445,
        157278, 248079, 133930,    349,    713,  75831,    452,  11657, 141057,
         47274, 116914, 124785,   6067,    248, 182071, 248075,  12013,  58409,
         12025, 246156,   3054,    705,      9, 104781,  76065,    108, 174693,
          3423, 140515,  18781,    202,    349,  14916, 248079,  82935,     87,
           796,    202,  53054,    502,  25914,  51744,    230,  30158, 199073,
           108,      9, 109267, 248079,   9089,    248,  75529,    351, 226047,
          6399, 200356, 248079,   2493, 109207, 181953, 248079,    540,  35883,
        120531, 248075,      2])


In [26]:
len(tokens['input_ids'][0])

75

In [27]:
token_embedding_layer(tokens['input_ids'][0][0]).shape

torch.Size([1024])

In [28]:
token_embeddings = token_embedding_layer(tokens['input_ids'][0])

print("Token Embedding Matrix shape", token_embeddings.shape)
token_embeddings

Token Embedding Matrix shape torch.Size([75, 1024])


tensor([[-5.0000e+00, -1.2725e+00, -9.3604e-01,  ..., -1.8297e+01,
         -9.1328e+00, -1.0672e+01],
        [ 2.6416e-01,  2.6831e-01,  2.0117e-01,  ...,  3.2715e+00,
         -3.2402e+00,  3.1738e+00],
        [ 4.3579e-01, -2.3352e-01,  2.6825e-02,  ...,  5.4648e+00,
          2.7129e+00,  5.5430e+00],
        ...,
        [ 8.5859e+00, -4.5391e+00, -4.7314e-01,  ..., -7.9529e-02,
          7.4844e+00, -7.5156e+00],
        [-2.4863e+00, -2.7515e-01,  5.6114e-03,  ...,  1.0180e+01,
         -7.2422e+00, -4.8047e+00],
        [-7.8320e-01, -9.0527e-01, -9.4482e-01,  ...,  3.1078e+01,
         -8.1494e-01, -8.7354e-01]], grad_fn=<MulBackward0>)

In [29]:
import plotly.express as px

token_embeddings_np = token_embeddings.detach().numpy()

fig = px.imshow(
    token_embeddings_np,
    color_continuous_scale="RdBu",
    labels=dict(x="Embedding Dimension", y="Token Index", color="Value"),
    title="Token Embedding Heatmap"
)

fig.update_xaxes(side="top")
fig.update_layout(height=500, width=900)
fig.show()

In [30]:
d = embedded_sentence.shape[-1]
d

2

In [31]:
d_q, d_k, d_v = 2, 2, 4

d_q, d_k, d_v


(2, 2, 4)

In [32]:
tf.random.set_seed(123)
W_query = tf.Variable(tf.random.uniform((d, d_q)), trainable=True)
W_key   = tf.Variable(tf.random.uniform((d, d_k)), trainable=True)
W_value = tf.Variable(tf.random.uniform((d, d_v)), trainable=True)

In [33]:
print(W_query.shape, W_key.shape, W_value.shape)

(2, 2) (2, 2) (2, 4)


In [34]:
W_query

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.12615311, 0.5727513 ],
       [0.2993133 , 0.5461836 ]], dtype=float32)>

In [35]:
W_key

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.88968754, 0.12354946],
       [0.7718717 , 0.6850728 ]], dtype=float32)>

In [36]:
W_value

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[0.48962688, 0.5857923 , 0.36451697, 0.6550509 ],
       [0.9075084 , 0.37557673, 0.6882372 , 0.25384045]], dtype=float32)>

In [37]:
embedded_sentence

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.03446851, -0.00357019],
       [-0.01995064, -0.00613034],
       [-0.01702313,  0.0238638 ],
       [ 0.00711641, -0.0311882 ]], dtype=float32)>

In [38]:
queries = tf.matmul(embedded_sentence, W_query)
keys    = tf.matmul(embedded_sentence, W_key)
values  = tf.matmul(embedded_sentence, W_value)

In [39]:
print("Queries shape", queries.shape)
queries

Queries shape (4, 2)


<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.0032797 ,  0.0177919 ],
       [-0.00435173, -0.01477505],
       [ 0.00499523,  0.003284  ],
       [-0.00843729, -0.01295855]], dtype=float32)>

In [40]:
print("Keys shape", keys.shape)
keys

Keys shape (4, 2)


<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.02791047,  0.00181273],
       [-0.02248167, -0.00666462],
       [ 0.00327452,  0.01424524],
       [-0.01774191, -0.02048696]], dtype=float32)>

In [41]:
print("Values shape", values.shape)
values

Values shape (4, 4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.01363673,  0.01885051,  0.01010722,  0.02167237],
       [-0.0153317 , -0.01398934, -0.01149147, -0.01462481],
       [ 0.01332162, -0.00100933,  0.01021874, -0.00509342],
       [-0.02481917, -0.00754482, -0.01887083, -0.00325521]],
      dtype=float32)>

In [42]:
omega = tf.matmul(queries, keys, transpose_b=True)

print("Omega shape", omega.shape)
print("Omega (Unnormalized attention weights)")
print(omega)

Omega shape (4, 4)
Omega (Unnormalized attention weights)
tf.Tensor(
[[ 1.2378997e-04 -1.9230950e-04  2.6418947e-04 -4.2269024e-04]
 [-1.4824187e-04  1.9630414e-04 -2.2472393e-04  3.7990365e-04]
 [ 1.4537228e-04 -1.3418775e-04  6.3138315e-05 -1.5590401e-04]
 [-2.5897895e-04  2.7604809e-04 -2.1222577e-04  4.1517476e-04]], shape=(4, 4), dtype=float32)


In [43]:
d_k = tf.cast(d_k, tf.float32)

scaled_omega = omega / tf.sqrt(d_k)

attention_weights = tf.nn.softmax(scaled_omega, axis=-1)

print("Attention Weights")
print(attention_weights)

Attention Weights
tf.Tensor(
[[0.2500319  0.24997602 0.2500567  0.24993531]
 [0.2499648  0.25002572 0.24995129 0.25005817]
 [0.2500293  0.24997987 0.25001478 0.24997605]
 [0.2499445  0.25003907 0.24995275 0.25006366]], shape=(4, 4), dtype=float32)


In [44]:
row_sums = tf.reduce_sum(attention_weights, axis=-1)

print("Sum of each row in attention_weights")
row_sums

Sum of each row in attention_weights


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.99999994, 1.        , 1.        , 0.99999994], dtype=float32)>

In [45]:
context_vector = tf.matmul(attention_weights, values)

print("Context Vector shape", context_vector.shape)
print(context_vector)

Context Vector shape (4, 4)
tf.Tensor(
[[-0.00329497 -0.00092188 -0.00250669 -0.00032431]
 [-0.0033011  -0.00092466 -0.00251133 -0.00032635]
 [-0.00329663 -0.00092225 -0.00250796 -0.00032434]
 [-0.0033017  -0.00092527 -0.00251178 -0.00032701]], shape=(4, 4), dtype=float32)


In [46]:
class SelfAttention(tf.keras.layers.Layer):
    def __init__(self, d_in, d_out_kq, d_out_v):
        super().__init__()
        self.d_out_kq = d_out_kq

        self.W_query = tf.Variable(
            tf.random.uniform((d_in, d_out_kq)), trainable=True
        )
        self.W_key = tf.Variable(
            tf.random.uniform((d_in, d_out_kq)), trainable=True
        )
        self.W_value = tf.Variable(
            tf.random.uniform((d_in, d_out_v)), trainable=True
        )

    def call(self, x):
        keys = tf.matmul(x, self.W_key)      # [T, d_out_kq]
        queries = tf.matmul(x, self.W_query) # [T, d_out_kq]
        values = tf.matmul(x, self.W_value)  # [T, d_out_v]

        # Attention scores: QKᵀ
        attn_scores = tf.matmul(queries, keys, transpose_b=True)  # [T, T]

        # Softmax (scaled by sqrt(d_k))
        attn_weights = tf.nn.softmax(
            attn_scores / tf.math.sqrt(tf.cast(self.d_out_kq, tf.float32)), axis=-1
        )  # [T, T]

        # Weighted sum
        context_vec = tf.matmul(attn_weights, values)  # [T, d_out_v]
        return context_vec

In [47]:
tf.random.set_seed(123)

d_in, d_out_kq, d_out_v = 2, 2, 4

sa = SelfAttention(d_in, d_out_kq, d_out_v)

out = sa(embedded_sentence)

print(out.shape)  # (T, d_out_v)
print(out.numpy())

(4, 4)
[[-0.00329497 -0.00092188 -0.00250669 -0.00032431]
 [-0.0033011  -0.00092466 -0.00251133 -0.00032635]
 [-0.00329663 -0.00092225 -0.00250796 -0.00032434]
 [-0.0033017  -0.00092527 -0.00251178 -0.00032701]]


In [48]:
class MultiHeadAttentionWrapper(tf.keras.layers.Layer):
    def __init__(self, d_in, d_out_kq, d_out_v, num_heads):
        super().__init__()
        self.heads = [
            SelfAttention(d_in, d_out_kq, d_out_v)
            for _ in range(num_heads)
        ]

    def call(self, x):
        # รันทุก head แล้ว concat ตามแกนสุดท้าย
        head_outputs = [head(x) for head in self.heads]   # list of [T, d_out_v]
        return tf.concat(head_outputs, axis=-1)           # [T, num_heads * d_out_v]

In [49]:
tf.random.set_seed(123)

d_in, d_out_kq, d_out_v = 2, 2, 1

sa = SelfAttention(d_in, d_out_kq, d_out_v)

# ถ้า embedded_sentence.shape = [T, d_in] เช่น [6, 3]
out = sa(embedded_sentence)

print(out.shape)   # (T, d_out_v) -> (6, 1)
print(out.numpy())

(4, 1)
[[-0.00192676]
 [-0.00193083]
 [-0.00192769]
 [-0.00193138]]


In [50]:
tf.random.set_seed(123)

mha = MultiHeadAttentionWrapper(
    d_in, d_out_kq, d_out_v, num_heads=3
)

# run MHA
context_vecs = mha(embedded_sentence)   # [T, num_heads * d_out_v]

print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

tf.Tensor(
[[-0.00192676 -0.00282132 -0.00305645]
 [-0.00193083 -0.00282642 -0.00306821]
 [-0.00192769 -0.00282392 -0.0030663 ]
 [-0.00193138 -0.00282585 -0.00306348]], shape=(4, 3), dtype=float32)
context_vecs.shape: (4, 3)
